### ISSUE TITLE
[Bug]: Failed to get collection info.

### ISSUE THREAD

**Issue by liwenchao1995** [zilliztech/milvus-backup#139]
### Current Behavior

this is my docker-compose.yml
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-/data/milvus2.2.9_data/dev}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-/data/milvus2.2.9_data/dev}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  attu:
    container_name: attu
    image: zilliz/attu:v2.2.5
    environment:
      MILVUS_URL: 192.168.10.26:19530
    ports:
      - "8000:3000"
    depends_on:
      - "standalone"


  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.9
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-/data/milvus2.2.9_data/dev}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

### Expected Behavior

"When I visit the page, I encounter an error message 'failed to show collections'. Upon checking the log, the error message is:"

[2023/06/12 06:11:08.477 +00:00] [WARN] [proxy/task.go:710] ["Failed to get collection info."] [collectionName=] [requestID=442119033574653955] [requestType=showCollections]
[2023/06/12 06:11:08.477 +00:00] [WARN] [proxy/task_scheduler.go:473] ["Failed to execute task: "] [error="failed to show collections"] [traceID=4f25e02e3031a50f]
[2023/06/12 06:11:08.477 +00:00] [WARN] [proxy/impl.go:1123] ["ShowCollections failed to WaitToFinish"] [error="failed to show collections"] [role=proxy] [MsgID=442119033574653955] [DbName=default] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[]"]
