### ISSUE TITLE
[Bug]: milvus-backup 0.3(1.0-beta) only backup meta,not including binlog in Milvus 2.2.10

### ISSUE THREAD

**Issue by minminggu** [zilliztech/milvus-backup#162]
### Current Behavior

After backing up the database, only the m
[backup.log](https://github.com/zilliztech/milvus-backup/files/12045786/backup.log)
eta directory is available in the backup directory "aiprodbak", and there are no binlog files. The meta directory contains only four files: segment_meta.json, partition_meta.json, collection_meta.json and backup_meta.json. The operating system is Debian.

### Steps To Reproduce

```markdown
1. download milvus-backup and check version
   ./milvus-backup version  ==>  Version: 1.0-beta
2. config backup.yaml
   ls -l  milvus-backup ==> OK
   mkdir configs 
   cd  configs 
   vi  backup.yaml
   cd ..
   ./milvus-backup create -n aiprodbak  ==> That's OK and success
```
  backup.log is uploaded.

### Environment

```markdown
Milvus version  2.2.10 is installed using K8S image. OS is Debian 5.10.179-1(uname -a).
```

### Anything else?

backup.yaml
```
# Configures the system log output.
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: IPADDRESS
  port: 30002
  authorizationEnabled: true
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "admin"
  password: "aaPASSWD"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: IPADDRESS  # Address of MinIO/S3
  port: 30080   # Port of MinIO/S3
  accessKeyID: minioaaa # accessKeyID of MinIO/S3
  secretAccessKey: minioaaa  # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""

  bucketName: "milvus-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "milvus-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G

```
