### ISSUE TITLE
[Bug]: only meta data is backuped

### ISSUE THREAD

**Issue by opt-m** [zilliztech/milvus-backup#163]
### Current Behavior

only meta data backuped

### Expected Behavior

both meta & vector data backuped

### Steps To Reproduce

```markdown
* milvus 2.2.10 standalone
    * storaged: s3
    * meta: etcd
* milvus backup  0.3.0 Linux_x86_64
```
* backup config:
```
# Configures the system log output.
log:
  level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: x.x.x.
  port: 19530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: xxxx # Address S3
  port: 80  # Port of MinIO/S3
  accessKeyID: xxxx
  secretAccessKey: xxxx
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: milvus-dep334-20011 # Bucket name in MinIO/S3
  rootPath: milvus-dep334-20011
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""


  backupBucketName: "milvus-dep334-20011" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G
```

* backup command : ./milvus-backup create -n backup

**only meta data backuped**
<img width="828" alt="image" src="https://github.com/zilliztech/milvus-backup/assets/18734311/57ee96a9-e9db-4cfb-9294-7905e8b4107f">
```


### Environment

_No response_

### Anything else?

_No response_
