### ISSUE TITLE
[Bug]: restore collection faild, no vector data has been recovered

### ISSUE THREAD

**Issue by yengogo** [zilliztech/milvus-backup#166]
### Current Behavior

I have successfully backed up the data to Minio, but after restoring, only the schema has been recovered, the vector data has not been restored. 
Moreover, the status of the collection is in 'unloaded' state. Could you please help me resolve this issue?

Here is the screenshot form attu 
![hello](https://github.com/zilliztech/milvus-backup/assets/61774146/8fe56d72-2873-418a-98cf-a166d3674477)
![hello2](https://github.com/zilliztech/milvus-backup/assets/61774146/e2628b49-b2ef-43da-81e6-e42226e21ed8)

### Environment

```markdown
milvus v2.2.10
milvus-backup v0.3.0
```

### Anything else?

⭐backup.yaml

```
  # Configures the system log output.
  log:
    level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
    console: true
    file:
      rootPath: "logs/backup.log"
  
  http:
    simpleResponse: true
  
  # milvus proxy address, compatible to milvus.yaml
  milvus:
    address: localhost
    port: 19530
    authorizationEnabled: false
    # tls mode values [0, 1, 2]
    # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
    tlsMode: 0
    user: "root"
    password: "Milvus"
  
  # Related configuration of minio, which is responsible for data persistence for Milvus.
  minio:
    address: localhost # Address of MinIO/S3
    port: 9000   # Port of MinIO/S3
    accessKeyID: minioadmin # accessKeyID of MinIO/S3
    secretAccessKey: minioadmin # MinIO/S3 encryption string
    useSSL: false # Access to MinIO/S3 with SSL
    useIAM: false
    cloudProvider: "aws"
    iamEndpoint: ""
    
    bucketName: "a-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
    rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance
  
    backupBucketName: "a-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
    backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath
  
  backup:
          maxSegmentGroupSize: 6G
```
