### ISSUE TITLE
help!!Fail to fill segment backup info

### ISSUE THREAD

**Issue by jjf956123364** [zilliztech/milvus-backup#277]
[2024/01/08 14:41:38.207 +08:00] [INFO] [core/backup_context.go:100] ["{Base:0xc00033a780 MaxSegmentGroupSize:2147483648 BackupCollectionParallelism:4 BackupCopyDataParallelism:128 RestoreParallelism:2 KeepTempFiles:false}"]
[2024/01/08 14:41:38.207 +08:00] [INFO] [core/backup_context.go:101] ["{Base:0xc00033a780 Enabled:true DebugMode:false SimpleResponse:true}"]
[2024/01/08 14:41:38.214 +08:00] [INFO] [core/backup_impl_create_backup.go:541] ["collections to backup"] [collections="[col_5e9119a34ee945ad8fa472311e04f09a]"]
[2024/01/08 14:41:38.214 +08:00] [INFO] [core/backup_impl_create_backup.go:225] ["start backup collection"] [db=default] [collection=col_5e9119a34ee945ad8fa472311e04f09a]
[2024/01/08 14:41:38.217 +08:00] [INFO] [core/backup_impl_create_backup.go:258] ["try to get index"] [collection_name=col_5e9119a34ee945ad8fa472311e04f09a]
[2024/01/08 14:41:38.223 +08:00] [INFO] [core/backup_impl_create_backup.go:278] ["field index"] [collection_name=col_5e9119a34ee945ad8fa472311e04f09a] [field_name=text] ["index info"="[{}]"]
[2024/01/08 14:41:38.229 +08:00] [INFO] [core/backup_impl_create_backup.go:278] ["field index"] [collection_name=col_5e9119a34ee945ad8fa472311e04f09a] [field_name=pk] ["index info"="[{}]"]
[2024/01/08 14:41:38.235 +08:00] [INFO] [core/backup_impl_create_backup.go:278] ["field index"] [collection_name=col_5e9119a34ee945ad8fa472311e04f09a] [field_name=vector] ["index info"="[{}]"]
[2024/01/08 14:41:38.243 +08:00] [INFO] [core/backup_impl_create_backup.go:366] ["GetPersistentSegmentInfo before flush from milvus"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a] [segmentNumBeforeFlush=1]
[2024/01/08 14:41:38.246 +08:00] [INFO] [core/backup_impl_create_backup.go:374] ["flush segments"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a] [newSealedSegmentIDs="[]"] [flushedSegmentIDs="[446758887299134173]"] [timeOfSeal=1704696098]
[2024/01/08 14:41:38.248 +08:00] [INFO] [core/backup_impl_create_backup.go:387] ["GetPersistentSegmentInfo after flush from milvus"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a] [segmentNumBeforeFlush=1] [segmentNumAfterFlush=1]
[2024/01/08 14:41:38.248 +08:00] [INFO] [core/backup_impl_create_backup.go:434] ["Finished fill segment"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a]
[2024/01/08 14:41:38.248 +08:00] [INFO] [core/backup_impl_create_backup.go:471] ["finish build partition info"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a] [partitionNum=1]
[2024/01/08 14:41:38.248 +08:00] [INFO] [core/backup_impl_create_backup.go:561] ["Finish flush all collections"]
[2024/01/08 14:41:38.249 +08:00] [INFO] [core/backup_impl_create_backup.go:499] ["Begin copy data"] [collectionName=col_5e9119a34ee945ad8fa472311e04f09a] [segmentNum=1]
[2024/01/08 14:41:38.249 +08:00] [ERROR] [core/backup_impl_create_backup.go:506] ["Fail to fill segment backup info"] [collection_id=446758887299134128] [partition_id=446758887299134129] [segment_id=446758887299134173] [group_id=0] [error="Get empty input path, but segment should not be empty, %sfiles/insert_log/446758887299134128/446758887299134129/446758887299134173/"] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).backupCollectionExecute\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:506\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func2\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:567\ngithub.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n\t/home/runner/work/milvus-backup/milvus-backup/internal/common/workerpool.go:70\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"]

备份的时候报错,能帮忙分析一下是什么原因吗？以下是我的backup.yaml
```
minio:
  # cloudProvider: "minio" # deprecated use storageType instead
  storageType: "minio" # support storage type: local, minio, s3, aws, gcp, ali(aliyun), azure

  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: minioadmin  # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  iamEndpoint: ""

  bucketName: "a-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  # only for azure
  backupAccessKeyID: minioadmin  # accessKeyID of MinIO/S3
  backupSecretAccessKey: minioadmin # MinIO/S3 encryption string

  backupBucketName: "a-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath
```
