### ISSUE TITLE
[Bug]: Pause Milvus GC response

### ISSUE THREAD

**Issue by suyestyle** [zilliztech/milvus-backup#433]
### Current Behavior

When I was doing a backup, I found the log message [Pause Milvus GC response]

### Steps To Reproduce

1、Started milvus and did port mapping
```
9091 --> 55002
```
2、backup conf
```
  gcPause:
    enable: true
    seconds: 7200
    address: http://localhost:55002
```

3、./milvus-backup create -n firstbackup

```
[2024/09/24 15:55:13.629 +08:00] [INFO] [core/backup_impl_create_backup.go:628] ["Pause Milvus GC response"] [response="404 page not found"] [address=http://localhost:55002] [pauseSeconds=7200]
```

### Environment

```
milvus 2.3.4
milvus-backup 0.4.24
```
