### ISSUE TITLE
[Bug]: Restore will fail if `backupBucketName` is different with `bucketName`

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#55]
### Current Behavior

when `backupBucketName` is different with `bucketName` in `backup.yaml`, the restored collection will be an empty collection.

Since restore rely on bulk insert, so the backup files should be in the same bucket as Milvus as bulk insert required.

**Comment by zhuwenxing** [comment]
success job:https://github.com/zhuwenxing/milvus-backup/actions/runs/3748887292/jobs/6366737653
```
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"
http:
  simpleResponse: true
# milvus proxy address, compatible to milvus.yaml
milvus:
  address: localhost
  port: [19](https://github.com/zhuwenxing/milvus-backup/actions/runs/3748887292/jobs/6366737653#step:6:20)530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"
# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: "milvus-bucket" # Bucket name in MinIO/S3
  rootPath: file # The root path where the message is stored in MinIO/S3
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  backupBucketName: "milvus-bucket"
  backupRootPath: "backup"
```

failed job: https://github.com/zhuwenxing/milvus-backup/actions/runs/3738507027/jobs/6344659911
```
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"
http:
  simpleResponse: true
# milvus proxy address, compatible to milvus.yaml
milvus:
  address: localhost
  port: [19](https://github.com/zhuwenxing/milvus-backup/actions/runs/3738507027/jobs/6344659911#step:6:20)530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"
# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  bucketName: "milvus-bucket" # Bucket name in MinIO/S3
  rootPath: file # The root path where the message is stored in MinIO/S3
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  backupBucketName: "a-bucket"
  backupRootPath: "backup"
```
