### ISSUE TITLE
[Bug]: Milvus proxy address effect is abnormal

### ISSUE THREAD

**Issue by maxhoov** [zilliztech/milvus-backup#617]
### Current Behavior

Milvus: 2.5.7
milvus-backup: 0.5.3

backup.yaml:
```
......

http:
  simpleResponse: true

milvus:
  address: milvus.proxy
  port: 19530
  user: "admin"
  password: "******"
  tlsMode: 0
  caCertPath: ""
  serverName: ""
  mtlsCertPath: ""
  mtlsKeyPath: ""

......

backup:
  maxSegmentGroupSize: 2G

  parallelism: 
    backupCollection: 4
    copydata: 128
    restoreCollection: 2
  
  keepTempFiles: false
  
  gcPause:
    enable: true
    seconds: 7200
    address: http://localhost:9091
```
When creating a new backup(milvus-backup create -n ...), the milvus proxy address defined in backup.yaml will be automatically appended with an inexplicable address (tcp://169.169.215.215:9530), which is not used anywhere in the system.

Full logs:
```
/app #./milvus-backup create -n milvus20250410
v0.5.3(Built on 2025-04-02T05:31:21Z from Git SHA f20e3ba)
config:backup.yaml
[2025/04/1014:17:43.433+00:00][INFO][logutil/logutil.go:165]["Log directory"][configDir-]
[2025/04/1014:17:43.433+00:00][INFO][loguti1/loguti1.go:166][Set log file to“][path-logs/backup.log]
[2025/04/1014:17:43.434+00:00][INPO][core/backup impl create backup.go:44]["receive CreateBackupRecuest"][reguest
1d-917b2c20-1616-11f0-82b4-32a2624809de][backupName=milvus_20250410][collections-"[]"][databaseCollections=][async=false][force=false][metaOnly=false]
[2025/04/1014:17:43.434+00:00][INFO][core/backup_context.go:87]["{Base:0xc000277508 MaxSegmentGroupSize:2147483648
BackupcollectionParallelism:4 BackupCopyDataParallelism:128 RestoreParallelism:2 KeepTempFiles:false GcPauseEnable:false GcPauseSeconds:7200 GcPauseAddress:http://localhost:9091}"]
[2025/04/1014:17:43.434+00:00][INFO][core/backup_context.go:88]["{Base:0xc000277508 Enabled:true DebugMode:false S
impleResponse:true}"]
[2025/04/1014:17:43.454+00:00][INFO][storage/minio_chunk_manager.go:144]["minio chunk manager init success."][buc
ketname=backup-bucket][root-backup]
[2025/04/1014:17:43.470 +00:00][INFO][client/grpc.go:241]["New milvus grpc client"][host=tcp://milvus.proxy:tcp://169.169.215.215:9530]
[2025/04/1014:17:43.471+00:00][WARN][grpclog/grpclog.go:155]["[core]Adjusting keepalive ping interval to minimum p
eriod of 10s"]
[2025/04/1014:17:43.471+00:00][ERROR][core/backup_impl_create_backup.go:97]["fail to get milvus version"][error-"client:get version failed: failed to exit idle mode: invalid target address tcp://milvus.proxy:tcp://169.1
69.215.215:9530, error info: address tcp://milvus.proxy:tcp://169.169.215.215:9530:443: too many colons in
address"][stack-"github.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup\n\t/app/core/backup_impl_create_backup.go:97\ngithub.com/zilliztech/milvus-backup/cmd.init.func3\n\t/app/cmd/create.go:62\ngithub.com/spf13/cobra.(*C
ommand).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).Executec\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Cormand).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/zilliztech/milvus-backup/cmd.Executelnt/app/cmd/root.go:35\nmain.main\n\t/app/main.go:19\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"]
client:get version failed: failed to exit idle mode: invalid target address tcp://milvus.proxy:tcp://169.169.215.215:9530,error info: address tcp://milvus.proxy:tcp://169.169.215.215:9530:443: too many colons in address
duration:0 s
```

### Steps To Reproduce

```markdown

```

### Environment

```markdown

```
