### ISSUE TITLE
[Bug]: Milvus-backup only restored the collection meta instead of index data

### ISSUE THREAD

**Issue by Leslie-Wong-H** [zilliztech/milvus-backup#86]
### Current Behavior

> git clone https://github.com/zilliztech/milvus-backup.git

> go get 

> go build 

> Change <code>config/backup.yaml</code> to my own s3 information.

> ./milvus-backup create -n my_backup 

>./milvus-backup restore -n  my_backup -s _recover

### Expected Behavior

I should see a new collection named <code>my_collection_recover</code> with the same stats as <code>my_collection_recover</code>, yet the new collection only has the metadata except for index data. 

![cadcef7c3a072e7c728fa99c6005609](https://user-images.githubusercontent.com/27696701/218103266-b935c4bd-ad8c-4625-aa0c-9b3ea87ecb41.png)

![3388be7344ddc9e1ae90a87787bd85e](https://user-images.githubusercontent.com/27696701/218103292-12d69278-b761-44f3-ae9a-802a19672d7f.png)

### Steps To Reproduce

```markdown
See above
```

### Environment

```markdown
Ubuntu 20.04 LTS
4 core 32 G ram
Docker Compose 
Milvus-Standalone 2.2.2
```

### Anything else?

Logs 
[backup.log](https://github.com/zilliztech/milvus-backup/files/10707895/backup.log)

**Comment by Leslie-Wong-H** [comment]
The backupBucket did receive files from the bucket, about 10~ GB. 

```yaml
# Configures the system log output.
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: localhost
  port: 19530
  authorizationEnabled: false
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: ****************** # accessKeyID of MinIO/S3
  secretAccessKey: ******************* # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  
  bucketName: "ultraman-shot" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "ultraman-shot-backup" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G

```
